export default {
  "Académica": "pt-AAC",
  "FC Arouca": "pt-AROU",
  "C.F. Os Belenenses": "pt-CFOB",
  "SL Benfica": "pt-SLB",
  "Boavista Porto FC": "pt-BOA",
  "Sporting Braga": "pt-SCB",
  "GD Estoril Praia": "pt-GDP",
  "Vitoria Guimaraes": "pt-VSC",
  "Maritimo Funchal": "pt-CSM",
  "Moreirense FC": "pt-MOR",
  "Nacional Funchal": "pt-CDN",
  "FC Paços de Ferreira": "pt-FCPF",
  "FC Porto": "pt-FCP",
  "FC Rio Ave": "pt-RAFC",
  "Vitoria Setubal": "pt-VFC",
  "Sporting CP": "pt-SCP",
  "CD Tondela": "pt-CDT",
  "U. Madeira": "pt-UMAD",
  "Atlético CP": "pt-ACP",
  "Desp. Aves": "pt-AVES",
  "G.D. Chaves": "pt-CVS",
  "Sp. Covilhã": "pt-SCC",
  "Farense": "pt-SCF",
  "Feirense": "pt-CDF",
  "Freamunde": "pt-FREA",
  "Famalicão": "pt-FAM",
  "Gil Vicente": "pt-GIL",
  "Leixões": "pt-LXO",
  "Mafra": "pt-CDM",
  "Olhanense": "pt-OLH",
  "Oliveirense": "pt-UDO",
  "Oriental": "pt-COL",
  "Penafiel": "pt-PEN",
  "Portimonens": "pt-PSC",
  "Santa Clara": "pt-SCLA",
  "Varzim": "pt-VAR",
  "Ac. Viseu": "pt-AVFC",
  "AD Fafe": "pt-ADF",
  "Mirandela": "pt-MIR",
  "Sintrense": "pt-SUS",
  "Alcochetens": "pt-ALC",
  "Cova da Piedade": "pt-CDCP",
  "Beira Mar": "pt-BEI",
  "U. Micaelense": "pt-CUM",
}